[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.(py|pyi)$'
exclude = '''
/(\.git|\.venv|build|dist|reports|__pycache__)/
'''

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
force_grid_wrap = 0
include_trailing_comma = true
multi_line_output = 3
known_first_party = ["ai_trader", "tests"]
