name: AidayTradingApp
options:
  minimumXcodeGenVersion: 2.37.0
  developmentRegion: en
  deploymentTarget:
    iOS: 16.0
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.22.0
settings:
  BASE_SDK: iphoneos
  SWIFT_VERSION: 5.9
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: ""
targets:
  AidayTradingApp:
    type: application
    platform: iOS
    sources:
      - path: Sources/AidayTradingApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aidaytrading.app
      INFOPLIST_FILE: Sources/AidayTradingApp/Application/Info.plist
    dependencies:
      - package: Firebase
        product: FirebaseMessaging
      - package: Firebase
        product: FirebaseCore
    scheme:
      testTargets:
        - AidayTradingAppTests
  AidayTradingAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/AidayTradingAppTests
    dependencies:
      - target: AidayTradingApp
