# Production-ready configuration for the AI trading stack
kraken:
  api_key: ""  # Populated from KRAKEN_API_KEY env var in production.
  api_secret: ""  # Populated from KRAKEN_API_SECRET env var in production.
  rest_rate_limit: 0.5

trading:
  base_currency: "USD"
  symbols:
    - "BTC/USD"
    - "ETH/USD"
    - "SOL/USD"
  equity_allocation_percent: 2.0
  max_open_positions: 3
  paper_trading: true
  paper_starting_equity: 25000.0
  allow_shorting: false
  min_cash_per_trade: 10.0
  max_cash_per_trade: 20.0
  trade_confidence_min: 0.5
  mode: "paper"  # Toggle to "live" only after loading env credentials and restarting the bot.

risk:
  max_drawdown_percent: 12.0
  daily_loss_limit_percent: 2.0
  max_position_duration_minutes: 120

ml:
  feature_keys:
    - momentum_1
    - momentum_3
    - momentum_5
    - momentum_10
    - rolling_volatility
    - atr
    - volume_delta
    - volume_ratio
    - volume_ratio_3
    - volume_ratio_10
    - body_pct
    - upper_wick_pct
    - lower_wick_pct
    - wick_close_ratio
    - range_pct
    - ema_fast
    - ema_slow
    - macd
    - macd_hist
    - rsi
    - zscore
    - close_to_high
    - close_to_low
  lr: 0.03
  regularization: 0.0005
  threshold: 0.5  # Raise towards 0.55–0.65 for stricter production gating.
  ensemble: true
  forest_size: 10
  random_state: 7
  warmup_samples: 25

workers:
  refresh_interval_seconds: 15
  definitions:
    btc_momentum:
      module: "ai_trader.workers.momentum.MomentumWorker"
      enabled: true
      display_name: "BTC Momentum Scout"
      emoji: "⚡"
      symbols:
        - "BTC/USD"
      parameters:
        fast_window: 10
        slow_window: 30
        warmup_candles: 5
        ml_threshold: 0.55
      risk:
        leverage: 1.0
        position_size_pct: 45.0
        stop_loss_pct: 1.2
        take_profit_pct: 2.4
        trailing_stop_pct: 0.9
    btc_mean_reversion:
      module: "ai_trader.workers.mean_reversion.MeanReversionWorker"
      enabled: true
      display_name: "BTC Mean Reverter"
      emoji: "🔄"
      symbols:
        - "BTC/USD"
      parameters:
        window: 28
        threshold: 0.012
        warmup_candles: 5
        ml_threshold: 0.52
      risk:
        leverage: 1.0
        position_size_pct: 40.0
        stop_loss_pct: 1.1
        take_profit_pct: 2.0
        trailing_stop_pct: 0.8
    eth_momentum:
      module: "ai_trader.workers.momentum.MomentumWorker"
      enabled: true
      display_name: "ETH Momentum Scout"
      emoji: "⚡"
      symbols:
        - "ETH/USD"
      parameters:
        fast_window: 9
        slow_window: 27
        warmup_candles: 5
        ml_threshold: 0.53
      risk:
        leverage: 1.0
        position_size_pct: 40.0
        stop_loss_pct: 1.3
        take_profit_pct: 2.3
        trailing_stop_pct: 0.9
    eth_mean_reversion:
      module: "ai_trader.workers.mean_reversion.MeanReversionWorker"
      enabled: true
      display_name: "ETH Mean Reverter"
      emoji: "🔁"
      symbols:
        - "ETH/USD"
      parameters:
        window: 26
        threshold: 0.013
        warmup_candles: 5
        ml_threshold: 0.5
      risk:
        leverage: 1.0
        position_size_pct: 38.0
        stop_loss_pct: 1.2
        take_profit_pct: 2.1
        trailing_stop_pct: 0.8
    sol_momentum:
      module: "ai_trader.workers.momentum.MomentumWorker"
      enabled: true
      display_name: "SOL Momentum Scout"
      emoji: "⚡"
      symbols:
        - "SOL/USD"
      parameters:
        fast_window: 8
        slow_window: 24
        warmup_candles: 6
        ml_threshold: 0.58
      risk:
        leverage: 1.0
        position_size_pct: 35.0
        stop_loss_pct: 1.5
        take_profit_pct: 3.0
        trailing_stop_pct: 1.1
    sol_mean_reversion:
      module: "ai_trader.workers.mean_reversion.MeanReversionWorker"
      enabled: true
      display_name: "SOL Mean Reverter"
      emoji: "🔁"
      symbols:
        - "SOL/USD"
      parameters:
        window: 24
        threshold: 0.018
        warmup_candles: 6
        ml_threshold: 0.56
      risk:
        leverage: 1.0
        position_size_pct: 32.0
        stop_loss_pct: 1.4
        take_profit_pct: 2.8
        trailing_stop_pct: 1.0
    research_btc:
      module: "ai_trader.workers.researcher.MarketResearchWorker"
      enabled: true
      display_name: "Research Sentinel (BTC)"
      emoji: "🔬"
      symbols:
        - "BTC/USD"
      parameters:
        warmup_candles: 5
        feature_windows:
          - 5
          - 14
          - 30
        timeframe: "1m"
        log_every_n_snapshots: 1
        volatility_window: 20
        ohlc_window: 20
    research_eth:
      module: "ai_trader.workers.researcher.MarketResearchWorker"
      enabled: true
      display_name: "Research Sentinel (ETH)"
      emoji: "🔬"
      symbols:
        - "ETH/USD"
      parameters:
        warmup_candles: 5
        feature_windows:
          - 5
          - 14
          - 30
        timeframe: "1m"
        log_every_n_snapshots: 1
        volatility_window: 20
        ohlc_window: 20
    research_sol:
      module: "ai_trader.workers.researcher.MarketResearchWorker"
      enabled: true
      display_name: "Research Sentinel (SOL)"
      emoji: "🔬"
      symbols:
        - "SOL/USD"
      parameters:
        warmup_candles: 5
        feature_windows:
          - 5
          - 14
          - 30
        timeframe: "1m"
        log_every_n_snapshots: 1
        volatility_window: 20
        ohlc_window: 20

dashboard:
  host: "0.0.0.0"
  port: 8501
  refresh_interval_seconds: 5
  default_symbol: "BTC/USD"
