# Live trading overrides applied when AI_TRADER_ENV=live
trading:
  mode: "live"
  paper_trading: false
  equity_allocation_percent: 1.0
  max_open_positions: 2
  allow_shorting: false
  min_cash_per_trade: 10.0
  max_cash_per_trade: 20.0
  trade_confidence_min: 0.6

risk:
  max_drawdown_percent: 8.0
  daily_loss_limit_percent: 1.5
  risk_per_trade: 0.01
  min_trades_per_day: 15
  confidence_relax_percent: 0.05

ml:
  threshold: 0.5
  warmup_samples: 50
  ensemble: true

workers:
  refresh_interval_seconds: 10
