# Example deployment flow:
# 1. Start in paper mode to validate signals and confidence while using paper balances.
# 2. Once satisfied, switch to live mode and ensure KRAKEN_API_KEY / KRAKEN_API_SECRET env vars are set.
#
# Copy this file to config.yaml and adjust symbols/risk per your strategy profile.
kraken:
  api_key: ""  # Leave blank – bot reads from environment variables in production.
  api_secret: ""
  rest_rate_limit: 0.5

trading:
  base_currency: "USD"
  symbols:
    - "BTC/USD"
    - "ETH/USD"
    - "SOL/USD"
  equity_allocation_percent: 2.0
  max_open_positions: 2
  paper_trading: true
  paper_starting_equity: 20000.0
  allow_shorting: false
  min_cash_per_trade: 10.0
  max_cash_per_trade: 20.0
  trade_confidence_min: 0.5
  mode: "paper"  # Toggle to "live" only after credentials + production risk checks.

risk:
  max_drawdown_percent: 10.0
  daily_loss_limit_percent: 1.5
  max_position_duration_minutes: 90

ml:
  lr: 0.03
  regularization: 0.0005
  threshold: 0.5
  ensemble: true
  forest_size: 10
  random_state: 7

workers:
  refresh_interval_seconds: 15
  definitions:
    btc_momentum:
      module: "ai_trader.workers.momentum.MomentumWorker"
      enabled: true
      display_name: "BTC Momentum Scout"
      symbols:
        - "BTC/USD"
      parameters:
        fast_window: 10
        slow_window: 30
        warmup_candles: 5
      risk:
        leverage: 1.0
        position_size_pct: 40.0
        stop_loss_pct: 1.2
        take_profit_pct: 2.4
        trailing_stop_pct: 0.9
    btc_mean_reversion:
      module: "ai_trader.workers.mean_reversion.MeanReversionWorker"
      enabled: true
      display_name: "BTC Mean Reverter"
      symbols:
        - "BTC/USD"
      parameters:
        window: 28
        threshold: 0.012
        warmup_candles: 5
      risk:
        leverage: 1.0
        position_size_pct: 35.0
        stop_loss_pct: 1.1
        take_profit_pct: 2.1
        trailing_stop_pct: 0.8
    eth_momentum:
      module: "ai_trader.workers.momentum.MomentumWorker"
      enabled: true
      display_name: "ETH Momentum Scout"
      symbols:
        - "ETH/USD"
      parameters:
        fast_window: 9
        slow_window: 27
        warmup_candles: 5
      risk:
        leverage: 1.0
        position_size_pct: 35.0
        stop_loss_pct: 1.3
        take_profit_pct: 2.3
        trailing_stop_pct: 0.9
    eth_mean_reversion:
      module: "ai_trader.workers.mean_reversion.MeanReversionWorker"
      enabled: true
      display_name: "ETH Mean Reverter"
      symbols:
        - "ETH/USD"
      parameters:
        window: 26
        threshold: 0.013
        warmup_candles: 5
      risk:
        leverage: 1.0
        position_size_pct: 32.0
        stop_loss_pct: 1.2
        take_profit_pct: 2.0
        trailing_stop_pct: 0.8
    sol_momentum:
      module: "ai_trader.workers.momentum.MomentumWorker"
      enabled: true
      display_name: "SOL Momentum Scout"
      symbols:
        - "SOL/USD"
      parameters:
        fast_window: 8
        slow_window: 24
        warmup_candles: 6
      risk:
        leverage: 1.0
        position_size_pct: 28.0
        stop_loss_pct: 1.5
        take_profit_pct: 3.0
        trailing_stop_pct: 1.1
    sol_mean_reversion:
      module: "ai_trader.workers.mean_reversion.MeanReversionWorker"
      enabled: true
      display_name: "SOL Mean Reverter"
      symbols:
        - "SOL/USD"
      parameters:
        window: 24
        threshold: 0.018
        warmup_candles: 6
      risk:
        leverage: 1.0
        position_size_pct: 26.0
        stop_loss_pct: 1.4
        take_profit_pct: 2.8
        trailing_stop_pct: 1.0
    research_btc:
      module: "ai_trader.workers.researcher.MarketResearchWorker"
      enabled: true
      display_name: "Research Sentinel (BTC)"
      symbols:
        - "BTC/USD"
      parameters:
        warmup_candles: 5
        feature_windows:
          - 5
          - 14
          - 30
        timeframe: "1m"
        log_every_n_snapshots: 1
    research_eth:
      module: "ai_trader.workers.researcher.MarketResearchWorker"
      enabled: true
      display_name: "Research Sentinel (ETH)"
      symbols:
        - "ETH/USD"
      parameters:
        warmup_candles: 5
        feature_windows:
          - 5
          - 14
          - 30
        timeframe: "1m"
        log_every_n_snapshots: 1
    research_sol:
      module: "ai_trader.workers.researcher.MarketResearchWorker"
      enabled: true
      display_name: "Research Sentinel (SOL)"
      symbols:
        - "SOL/USD"
      parameters:
        warmup_candles: 5
        feature_windows:
          - 5
          - 14
          - 30
        timeframe: "1m"
        log_every_n_snapshots: 1

