# Live trading overrides applied when AI_TRADER_ENV=live
trading:
  mode: "live"
  paper_trading: false
  equity_allocation_percent: 1.0
  max_open_positions: 2
  allow_shorting: true
  min_cash_per_trade: 15.0

risk:
  max_drawdown_percent: 8.0
  daily_loss_limit_percent: 1.5

ml:
  threshold: 0.4
  warmup_samples: 50
  ensemble: true

workers:
  refresh_interval_seconds: 10
