# Production-ready configuration for the AI trading stack
kraken:
  api_key: ""  # Populated from KRAKEN_API_KEY env var in production.
  api_secret: ""  # Populated from KRAKEN_API_SECRET env var in production.
  rest_rate_limit: 0.5

trading:
  base_currency: "USD"
  symbols:
    - "BTC/USD"
    - "ETH/USD"
  equity_allocation_percent: 2.0
  max_open_positions: 3
  paper_trading: true
  paper_starting_equity: 25000.0
  allow_shorting: true
  mode: "paper"  # Toggle to "live" only after loading env credentials and restarting the bot.

risk:
  max_drawdown_percent: 12.0
  daily_loss_limit_percent: 2.0
  max_position_duration_minutes: 120

ml:
  feature_keys:
    - momentum_1
    - momentum_3
    - momentum_5
    - momentum_10
    - rolling_volatility
    - atr
    - volume_delta
    - volume_ratio
    - volume_ratio_3
    - volume_ratio_10
    - body_pct
    - upper_wick_pct
    - lower_wick_pct
    - wick_close_ratio
    - range_pct
    - ema_fast
    - ema_slow
    - macd
    - macd_hist
    - rsi
    - zscore
    - close_to_high
    - close_to_low
  lr: 0.03
  regularization: 0.0005
  threshold: 0.25  # Raise towards 0.55–0.65 for stricter production gating.
  ensemble: true
  forest_size: 10
  random_state: 7

workers:
  refresh_interval_seconds: 15
  definitions:
    short_momentum:
      module: "ai_trader.workers.short_momentum.ShortMomentumWorker"
      enabled: true
      symbols:
        - "BTC/USD"
        - "ETH/USD"
      parameters:
        fast_window: 12
        slow_window: 48
        momentum_threshold: 0.004
        warmup_candles: 2
        ml_threshold: 0.35
      risk:
        leverage: 1.0
        position_size_pct: 35.0
        stop_loss_pct: 1.0
        take_profit_pct: 2.0
        trailing_stop_pct: 0.8
    short_mean_reversion:
      module: "ai_trader.workers.short_mean_reversion.ShortMeanReversionWorker"
      enabled: true
      symbols:
        - "BTC/USD"
      parameters:
        band_window: 20
        band_std_dev: 2.4
        warmup_candles: 2
        ml_threshold: 0.32
        reversion_threshold: 0.0035
      risk:
        leverage: 1.0
        position_size_pct: 30.0
        stop_loss_pct: 0.9
        take_profit_pct: 1.8
        trailing_stop_pct: 0.6
    ml_short:
      module: "ai_trader.workers.ml_short.MLShortWorker"
      enabled: true
      symbols:
        - "BTC/USD"
        - "ETH/USD"
      parameters:
        feature_lookback: 30
        probability_threshold: 0.3
        warmup_candles: 2
        ml_threshold: 0.35
      risk:
        leverage: 1.0
        position_size_pct: 30.0
        stop_loss_pct: 1.0
        take_profit_pct: 2.0
        trailing_stop_pct: 0.7

researcher:
  module: "ai_trader.workers.researcher.MarketResearchWorker"
  enabled: true
  symbols:
    - "BTC/USD"
    - "ETH/USD"
  parameters:
    warmup_candles: 2  # Increase to 20+ candles before going live for steadier signals.
    feature_windows:
      - 5
      - 14
      - 30
    timeframe: "1m"
    log_every_n_snapshots: 1
    volatility_window: 20
    ohlc_window: 20

dashboard:
  host: "0.0.0.0"
  port: 8501
  refresh_interval_seconds: 5
  default_symbol: "BTC/USD"
