kraken:
  api_key: ""
  api_secret: ""
  rest_rate_limit: 0.5

trading:
  base_currency: USD
  symbols:
    - BTC/USD
    - ETH/USD
    - SOL/USD
  equity_allocation_percent: 10.0
  max_open_positions: 2
  paper_trading: true
  paper_starting_equity: 200.0
  allow_shorting: false
  min_cash_per_trade: 10.0
  max_cash_per_trade: 20.0
  trade_confidence_min: 0.6
  trade_fee_percent: 0.0026
  min_order_value: 10.0

risk:
  max_drawdown_percent: 20.0
  daily_loss_limit_percent: 5.0
  max_position_duration_minutes: 240
  risk_per_trade: 0.02
  max_open_positions: 3
  min_trades_per_day: 30
  confidence_relax_percent: 0.1
  atr_stop_loss_multiplier: 1.5
  atr_take_profit_multiplier: 2.5
  atr_period: 14
  min_stop_buffer: 0.005
  telegram:
    enabled: true
    bot_token: ""
    chat_id: ""
    heartbeat_hours: 6

ml:
  feature_keys:
    - momentum_1
    - momentum_3
    - momentum_5
    - momentum_10
    - rolling_volatility
    - atr
    - volume_delta
    - volume_ratio
    - volume_ratio_3
    - volume_ratio_10
    - body_pct
    - upper_wick_pct
    - lower_wick_pct
    - wick_close_ratio
    - range_pct
    - ema_fast
    - ema_slow
    - macd
    - macd_hist
    - rsi
    - zscore
    - close_to_high
    - close_to_low
  learning_rate: 0.23
  regularization: 0.0005
  threshold: 0.35
  ensemble: true
  forest_size: 10
  random_state: 7
  warmup_samples: 25
  enabled: true

workers:
  refresh_interval_seconds: 15
  definitions:
    btc_momentum:
      module: ai_trader.workers.momentum.MomentumWorker
      enabled: true
      display_name: BTC Momentum Scout
      emoji: "⚡"
      symbols:
        - BTC/USD
      parameters:
        fast_window: 10
        slow_window: 30
        warmup_candles: 5
        ml_threshold: 0.55
      risk:
        leverage: 1.0
        position_size_pct: 100.0
        stop_loss_pct: 1.2
        take_profit_pct: 2.4
        trailing_stop_pct: 0.9
    btc_mean_reversion:
      module: ai_trader.workers.mean_reversion.MeanReversionWorker
      enabled: true
      display_name: BTC Mean Reverter
      emoji: "🔄"
      symbols:
        - BTC/USD
      parameters:
        window: 28
        threshold: 0.012
        warmup_candles: 5
        ml_threshold: 0.52
      risk:
        leverage: 1.0
        position_size_pct: 100.0
        stop_loss_pct: 1.1
        take_profit_pct: 2.0
        trailing_stop_pct: 0.8
    eth_momentum:
      module: ai_trader.workers.momentum.MomentumWorker
      enabled: true
      display_name: ETH Momentum Scout
      emoji: "⚡"
      symbols:
        - ETH/USD
      parameters:
        fast_window: 9
        slow_window: 27
        warmup_candles: 5
        ml_threshold: 0.53
      risk:
        leverage: 1.0
        position_size_pct: 100.0
        stop_loss_pct: 1.3
        take_profit_pct: 2.3
        trailing_stop_pct: 0.9
    eth_mean_reversion:
      module: ai_trader.workers.mean_reversion.MeanReversionWorker
      enabled: true
      display_name: ETH Mean Reverter
      emoji: "🔁"
      symbols:
        - ETH/USD
      parameters:
        window: 26
        threshold: 0.013
        warmup_candles: 5
        ml_threshold: 0.5
      risk:
        leverage: 1.0
        position_size_pct: 100.0
        stop_loss_pct: 1.2
        take_profit_pct: 2.1
        trailing_stop_pct: 0.8
    sol_momentum:
      module: ai_trader.workers.momentum.MomentumWorker
      enabled: true
      display_name: SOL Momentum Scout
      emoji: "⚡"
      symbols:
        - SOL/USD
      parameters:
        fast_window: 8
        slow_window: 24
        warmup_candles: 5
        ml_threshold: 0.54
      risk:
        leverage: 1.0
        position_size_pct: 100.0
        stop_loss_pct: 1.4
        take_profit_pct: 2.6
        trailing_stop_pct: 0.9
    sol_mean_reversion:
      module: ai_trader.workers.mean_reversion.MeanReversionWorker
      enabled: true
      display_name: SOL Mean Reverter
      emoji: "🔁"
      symbols:
        - SOL/USD
      parameters:
        window: 24
        threshold: 0.015
        warmup_candles: 5
        ml_threshold: 0.51
      risk:
        leverage: 1.0
        position_size_pct: 100.0
        stop_loss_pct: 1.3
        take_profit_pct: 2.4
        trailing_stop_pct: 0.85
