name: Backend QA

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run black
        run: black --check app tests

      - name: Run flake8
        run: flake8 app tests

      - name: Run pytest
        run: pytest -q --maxfail=1 --disable-warnings --timeout=20

      - name: Build docker image
        run: docker build -t aidaytrading-backend .
