settings:
  mode: live
  exchange: kraken
  api_key: ""
  api_secret: ""
  balance: 200
  loop_delay: 45
  warmup_candles: 20
  timeframe: 1m
  lookback: 300
  feed_workers: 4
  request_timeout: 30
  kraken_session: {}

feed:
  exchange: kraken
  symbols:
    - BTC/USD
    - ETH/USD
    - SOL/USD
  timeframe: 1m
  data_seeding:
    seed_length: 600
    max_stale_seconds: 600

risk:
  fixed_risk_usd: 20
  rr_ratio: 2.0
  stop_loss_pct: 0.02
  max_hold_minutes: 20
  daily_dd: null
  weekly_dd: null
  max_concurrent: 5
  halt_on_dd: true
  retrain_every: 15
  ml_weight: 0.6
  trapdoor_pct: 0.015
  weekly_return_target: 1.0
  trading_days_per_week: 5
  expected_trades_per_day: null
  slippage_bps: 15
  balance_buffer_pct: 0.05
  duplicate_cooldown_seconds: 90
  learning_risk:
    initial_multiplier: 1.5
    floor_multiplier: 0.85
    tighten_trades: 100
    target_win_rate: 0.6

portfolio:
  min_weight: 0.05
  max_weight: 0.3
  epsilon: 0.1
  cooldown_minutes: 10

telemetry:
  endpoint: ""
  flush_interval: 1.0
  max_backoff: 30.0

ml:
  target_win_rate: 0.58
  min_samples: 150

workers:
  - name: BTC Momentum
    symbol: BTC/USD
    strategy: momentum
    allocation: 0.20
    params:
      length: 20
      threshold: 0.65
      risk_per_trade: 0.35
    risk_profile:
      initial_multiplier: 1.5
      floor_multiplier: 0.85
      tighten_trades: 100
      target_win_rate: 0.6

  - name: BTC Mean Reversion
    symbol: BTC/USD
    strategy: rsi_mean_reversion
    allocation: 0.20
    params:
      length: 14
      low: 30
      high: 70
      risk_per_trade: 0.35
    risk_profile:
      initial_multiplier: 1.5
      floor_multiplier: 0.85
      tighten_trades: 100
      target_win_rate: 0.6

  - name: ETH Breakout
    symbol: ETH/USD
    strategy: ema_breakout
    allocation: 0.20
    params:
      length: 50
      risk_per_trade: 0.35
    risk_profile:
      initial_multiplier: 1.5
      floor_multiplier: 0.85
      tighten_trades: 100
      target_win_rate: 0.6

  - name: SOL Trend
    symbol: SOL/USD
    strategy: macd_trend
    allocation: 0.20
    params:
      fast: 12
      slow: 26
      signal: 9
      risk_per_trade: 0.35
    risk_profile:
      initial_multiplier: 1.5
      floor_multiplier: 0.85
      tighten_trades: 100
      target_win_rate: 0.6

  - name: ETH Volatility Fade
    symbol: ETH/USD
    strategy: bollinger_band
    allocation: 0.20
    params:
      length: 20
      mult: 2.5
      risk_per_trade: 0.35
    risk_profile:
      initial_multiplier: 1.5
      floor_multiplier: 0.85
      tighten_trades: 100
      target_win_rate: 0.6
