name: QA Pipeline

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (flake8)
        run: flake8 . --max-line-length=100 --exclude=.venv

      - name: Format check (black)
        run: black --check .

      - name: Run tests (pytest)
        run: pytest -q --maxfail=1 --disable-warnings --timeout=20
