name: QA Pipeline

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pytest
        run: |
          mkdir -p reports
          pytest --maxfail=1 --disable-warnings -q --cov=ai_trader --cov-report=xml:reports/coverage.xml --junitxml=reports/pytest.xml

      - name: Run flake8
        run: flake8 .

      - name: Run black check
        run: black --check .

      - name: Regression comparison
        run: python tests/regression/compare_regression.py

      - name: Upload QA artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qa-reports
          path: |
            reports/
            .coverage
            tests/regression/baseline_equity.json
          if-no-files-found: warn
